/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Sat Oct 26 03:41:28 2024"
#define BUILD_TIME (1729903288UL)

#define VERSION_NUMBER 0x04020014UL
#define EARLIEST_COMPATIBLE_VERSION_NUMBER 0x04020001UL
#define VERSION_FEATURES 0x000e0040UL
#define IGNORED_FEATURES 0x18080040UL
#define VERSION_SANITY1 0x443c01ffUL
#define VERSION_SANITY2 0x282c1040UL
#define VERSION_SANITY3 0x00524570UL
#define VERSION_SHORTSIZE 2
#define VERSION_INTSIZE 4
#define VERSION_LONGSIZE 8
#define VERSION_PTRSIZE 8

#define VERSION_STRING "4.2.0 (Build 20)"
#define VERSION_ID \
 "Unix GnollHack Version 4.2.0 (Build 20) - last build Sat Oct 26 03:41:28 2024."
#define COPYRIGHT_BANNER_C \
 "         Version 4.2.0 (Build 20) Unix, built Oct 26 03:41:28 2024."

