/* This source file is generated by 'makedefs'.  Do not edit. */
#ifndef ANIMTOTALS_H
#define ANIMTOTALS_H

#define	TOTAL_NUM_ANIMATION_FRAMES	13499
#define	TOTAL_NUM_ENLARGEMENT_TILES	10465
#define	TOTAL_NUM_REPLACEMENT_GLYPHS	1185

#endif /* ANIMTOTALS_H */
