/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Mon Jun 16 17:09:47 2025"
#define BUILD_TIME (1750082987UL)

#define VERSION_NUMBER 0x04020033UL
#define EARLIEST_COMPATIBLE_VERSION_NUMBER 0x04020001UL
#define VERSION_FEATURES 0x000e0000UL
#define IGNORED_FEATURES 0x18080040UL
#define VERSION_SANITY1 0x443c01ffUL
#define VERSION_SANITY2 0x282c1040UL
#define VERSION_SANITY3 0x00524570UL
#define VERSION_SHORTSIZE 2
#define VERSION_INTSIZE 4
#define VERSION_LONGSIZE 4
#define VERSION_PTRSIZE 8

#define VERSION_STRING "4.2.0 (Build 51)"
#define VERSION_ID \
 "Windows GnollHack Version 4.2.0 (Build 51) - last build Mon Jun 16 17:09:47 2025."
#define COPYRIGHT_BANNER_C \
 "         Version 4.2.0 (Build 51) Windows, built Jun 16 17:09:47 2025."

